### ISSUE TITLE
"High severity" security vulnerability affecting latest release (v2.0.0)

### ISSUE THREAD

**Issue by OronNadiv** [expressjs/connect-multiparty#20]
The latest version of `connect-multiparty` (v2.0.0) uses `qs` with semver ~4.  The [following vulnerability ](https://snyk.io/vuln/npm:qs:20170213) was recently discovered and is currently affecting `connect-multiparty` v2.0.0.

**Comment by dougwilson** [comment]
Duplicate of https://github.com/expressjs/connect-multiparty/pull/19
