### ISSUE TITLE
About article last word

### ISSUE THREAD

**Issue by SunOfHomeBoy** [expressjs/connect-multiparty#23]
## First question
"If you pass options to multipart(), they are passed directly into multiparty."
Excuse me, what does this sentence mean?

![image](https://user-images.githubusercontent.com/30047595/42297568-fe2dc8a0-8032-11e8-8aaf-018fa609d6b8.png)

look like my code,not use variable.What's wrong with that?

## Second question
`connect-multiparty` & `multiparty` ,these two libraries,what is the difference?

**Comment by dougwilson** [comment]
Hi @SunOfHomeBoy it means that any argument you pass to `multipart()` will be passed into the `multiparty` module .

> look like my code,not use variable.What's wrong with that?

I don't see anything wrong with your code. What is wrong with it?

> connect-multiparty & multiparty ,these two libraries,what is the difference?

The former is an express / connect middleware. The latter is a standalone module for use with any platform.
