### ISSUE TITLE
upload file save local

### ISSUE THREAD

**Issue by iysf** [expressjs/connect-multiparty#24]
怎么获取到文件本身？再将这个文件传给其他服务器

**Comment by sant123** [comment]
May you write your issue in English? 

Thank you!

**Comment by dougwilson** [comment]
I ran it through Google Translate, so I can only assume this is the right translation:

> How to get the file itself? Then pass this file to other servers.

The answer for this is use the `multiparty` module directly; you can pass the file directly to the server without writing to disk using the underlying module. If you want to do it with this module, you can file the file path of the uploaded file in `req.files`.

**Comment by iysf** [comment]
Thank you!
