### ISSUE TITLE
Uploading a file from Postman/Futter

### ISSUE THREAD

**Issue by daniwaxman** [expressjs/connect-multiparty#26]
I am trying to upload a file via Postman (also tried via flutter). In both cases I am getting an error 
"Cannot read property 'path' of undefined"
 When I inspect the req.file I see it is empty.

I have seen others who had this issue but did not see a resolution.

I am on 2.2.0

**Comment by dougwilson** [comment]
Thanks for the report. Can you provide the full stack trace for the error and/or an example app I can run and reproduce the error?

**Comment by dougwilson** [comment]
Closing due to no response.
