### ISSUE TITLE
Unlink file when request timed out

### ISSUE THREAD

**Issue by wellermiranda** [expressjs/connect-multiparty#27]
When I tried to upload long files and the request timed out (I'm using connect-timeout), only a part of the file was uploaded. I think adding this could solve the problem:

```
    form.parse(req);

    req.on('close', () => {
      if(form.bytesReceived !== form.bytesExpected) {
        form.openedFiles.forEach(({ publicFile: { path }}) => fs.unlinkSync(path))
      }
    })```

**Comment by wellermiranda** [comment]
Maybe expose the form data into req object should be a good alternative, then we can make our own treatment.

```
req.form = new multiparty.Form(options);
```

instead of

```
var form = new multiparty.Form(options);
```

**Comment by dougwilson** [comment]
For both those things, at that point just use multiparty directly. This module is just in maintenance mode for the existing simple use cases. Using multiparty directly is also very little code.
