### ISSUE TITLE
TypeError: os.tmpDir is not a function

### ISSUE THREAD

**Issue by queroin** [expressjs/connect-multiparty#31]
Hello and thank you for this package. Since we upgraded to NodeJS v16.11.0, we are encountering this issue

```
TypeError: os.tmpDir is not a function
  aop:server:error     at new Form (......\node_modules\multiparty\index.js:55:44)
  aop:server:error     at multipart (......\node_modules\connect-multiparty\index.js:56:16)
```

Would it be feasible to apply my suggested change?

Resolution: 
in `.\multiparty\index.js`

FROM
```
self.uploadDir = options.uploadDir || os.tmpDir();
```

TO
```
self.uploadDir = options.uploadDir || os.tmpdir();
```

Regards,

**Comment by queroin** [comment]
I just found out that we can use 'multiparty' module directly.

**Comment by dougwilson** [comment]
Yep. Another option is to user version 2.1.0 or higher of this module (https://github.com/expressjs/connect-multiparty/blob/master/HISTORY.md#210--2017-10-19).
